import test from "node:test";
import assert from "node:assert/strict";
import { createPlatformOperationsOverviewHandler } from "../netlify/functions/platform-operations-overview.mjs";
import { createPlatformOperationsDiagnosticsHandler } from "../netlify/functions/platform-operations-diagnostics.mjs";
import { createPlatformOperationsV2ActivationHandler } from "../netlify/functions/platform-operations-v2-activation.mjs";
import { validateDiagnosticV2Activation } from "../netlify/lib/platform-operations-v2-activation.mjs";

const auth=async()=>({ok:true,value:{userId:"user_operator",workspaceId:"11111111-1111-4111-8111-111111111111",authority:"platform-operator"}});
const request=(path,method="GET",body,origin="https://example.com")=>new Request(`https://example.com${path}`,{method,headers:{origin,...(body?{"content-type":"application/json"}:{})},body:body?JSON.stringify(body):undefined});
test("platform overview returns only the minimized tenant-bounded control view",async()=>{const overview={workspace:{label:"Northstar",status:"active"},summary:{diagnostics:1,activePocs:1,participantsCompleted:5,itemsNeedingReview:0},diagnostics:[]};const handler=createPlatformOperationsOverviewHandler({authenticate:auth,getOverview:async value=>{assert.match(value.workspaceId,/^1111/);return overview;}});const response=await handler(request("/api/operations/overview"));assert.equal(response.status,200);const body=await response.json();assert.deepEqual(body.workspace,overview.workspace);assert.equal(body.policy.participantContentIncluded,false);assert.equal((await handler(request("/api/operations/overview","POST"))).status,405);assert.equal((await handler(request("/api/operations/overview","GET",undefined,"https://attacker.example"))).status,403);});
test("only platform operations creates diagnostic engagements",async()=>{let created;const diagnostic={id:"22222222-2222-4222-8222-222222222222",route:"automated",entitlementType:"poc",entitlementStatus:"active"};const handler=createPlatformOperationsDiagnosticsHandler({authenticate:auth,listDiagnostics:async()=>[diagnostic],createDiagnostic:async value=>{created=value;return diagnostic;}});assert.equal((await handler(request("/api/operations/diagnostics"))).status,200);const response=await handler(request("/api/operations/diagnostics","POST",{route:"automated",entitlementType:"poc"}));assert.equal(response.status,201);assert.equal(created.actorUserId,"user_operator");assert.deepEqual(created.draft,{route:"automated",entitlementType:"poc"});});

test("only platform operations explicitly activates approved Protocol v2 collection",async()=>{let received;const handler=createPlatformOperationsV2ActivationHandler({authenticate:auth,activate:async value=>{received=value;return {diagnosticId:value.input.diagnosticId,interviewVersion:"2.0.0"};}});const payload={diagnosticId:"22222222-2222-4222-8222-222222222222",activationNote:"Approved frame and protocol are ready for controlled participant collection."};const response=await handler(request("/api/operations/diagnostic-v2-activation","POST",payload));assert.equal(response.status,201);assert.equal(received.userId,"user_operator");assert.deepEqual(received.input,validateDiagnosticV2Activation(payload));assert.equal((await handler(request("/api/operations/diagnostic-v2-activation"))).status,405);});
