import test from "node:test";
import assert from "node:assert/strict";
import { createPlatformOperationsOverviewHandler } from "../netlify/functions/platform-operations-overview.mjs";
import { createPlatformOperationsDiagnosticsHandler } from "../netlify/functions/platform-operations-diagnostics.mjs";

const auth=async()=>({ok:true,value:{userId:"user_operator",workspaceId:"11111111-1111-4111-8111-111111111111",authority:"platform-operator"}});
const request=(path,method="GET",body,origin="https://example.com")=>new Request(`https://example.com${path}`,{method,headers:{origin,...(body?{"content-type":"application/json"}:{})},body:body?JSON.stringify(body):undefined});
test("platform overview returns only the minimized tenant-bounded control view",async()=>{const overview={workspace:{label:"Northstar",status:"active"},summary:{diagnostics:1,activePocs:1,participantsCompleted:5,itemsNeedingReview:0},diagnostics:[]};const handler=createPlatformOperationsOverviewHandler({authenticate:auth,getOverview:async value=>{assert.match(value.workspaceId,/^1111/);return overview;}});const response=await handler(request("/api/operations/overview"));assert.equal(response.status,200);const body=await response.json();assert.deepEqual(body.workspace,overview.workspace);assert.equal(body.policy.participantContentIncluded,false);assert.equal((await handler(request("/api/operations/overview","POST"))).status,405);assert.equal((await handler(request("/api/operations/overview","GET",undefined,"https://attacker.example"))).status,403);});
test("only platform operations creates diagnostic engagements",async()=>{let created;const diagnostic={id:"22222222-2222-4222-8222-222222222222",route:"automated",entitlementType:"poc",entitlementStatus:"active"};const handler=createPlatformOperationsDiagnosticsHandler({authenticate:auth,listDiagnostics:async()=>[diagnostic],createDiagnostic:async value=>{created=value;return diagnostic;}});assert.equal((await handler(request("/api/operations/diagnostics"))).status,200);const response=await handler(request("/api/operations/diagnostics","POST",{route:"automated",entitlementType:"poc"}));assert.equal(response.status,201);assert.equal(created.actorUserId,"user_operator");assert.deepEqual(created.draft,{route:"automated",entitlementType:"poc"});});
