import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

const root=new URL("../",import.meta.url);
const publicPages=["404.html","about.html","assessment.html","capacity-brief-example.html","contact.html","diagnostic.html","framework.html","index.html","insights.html","organization-view.html","platform-journey.html","privacy.html","saved-results.html","signs.html"];
const canonicalLinks=[["framework.html","Capacity Lens"],["diagnostic.html","Diagnostic"],["assessment.html","Assessment"],["platform-journey.html","Platform Journey"],["signs.html","Signs"],["insights.html","Insights"],["about.html","About"],["contact.html","Connect"]];

test("every public page uses the canonical top-level navigation",async()=>{for(const page of publicPages){const html=await readFile(new URL(page,root),"utf8");const header=html.match(/<header class="site-header">[\s\S]*?<\/header>/)?.[0]||"";assert.match(header,/class="nav-toggle"/,`${page} needs the mobile navigation control`);assert.match(header,/class="site-nav"/,`${page} needs the canonical navigation`);assert.match(html,/src="script\.js"/,`${page} needs shared navigation behavior`);for(const[href,label]of canonicalLinks)assert.match(header,new RegExp(`<a href="${href}"(?: aria-current="page")?>${label}<\\/a>`),`${page} is missing ${label}`)}});

test("every public page uses the shared Senger wordmark treatment",async()=>{for(const page of publicPages){const html=await readFile(new URL(page,root),"utf8");const header=html.match(/<header class="site-header">[\s\S]*?<\/header>/)?.[0]||"";assert.match(header,/<a class="brand" href="index\.html" aria-label="Senger Advisory home"><span>Senger<\/span> <span>Advisory<\/span><\/a>/,`${page} needs the shared Senger wordmark`)}});

test("private and proprietary diagnostic surfaces are not added to public navigation",async()=>{for(const page of publicPages){const html=await readFile(new URL(page,root),"utf8");const header=html.match(/<header class="site-header">[\s\S]*?<\/header>/)?.[0]||"";assert.doesNotMatch(header,/workspace\/|diagnostic-(?:process|interview|synthesis|decision|workspace)/)}});

test("homepage begins with executive recognition and one controlled contextual response",async()=>{const[html,script,styles,engine,northStar]=await Promise.all(["index.html","script.js","styles.css","flow-engine.js","docs/Experience-North-Star.md"].map(file=>readFile(new URL(file,root),"utf8")));assert.match(html,/Your strategy may be sound/);assert.match(html,/Is this you\?/);assert.match(html,/The cost of waiting/);assert.equal((html.match(/data-capacity-concern=/g)||[]).length,6);assert.match(html,/This is not a diagnosis/);assert.match(script,/const concerns = \{/);assert.match(script,/aria-pressed/);assert.match(script,/setNarrativeStage\(concern\.stage\)/);assert.doesNotMatch(script,/\[3500, "complexity"\]|\[7000, "friction"\]/);assert.match(styles,/\.recognition-experience/);assert.match(styles,/\.urgency-consequences/);assert.match(engine,/setNarrativeStage\(stage\)/);assert.match(northStar,/I always know where I am, why this matters, what I need to do, and what happens next/)});

test("major public pages share a five-stage orientation and one explicit next move",async()=>{const[script,styles]=await Promise.all(["script.js","styles.css"].map(file=>readFile(new URL(file,root),"utf8")));assert.match(script,/Where you are · Step \$\{position \+ 1\} of \$\{stages\.length\}/);assert.match(script,/What happens next/);assert.match(script,/Why the current stage matters|why:/);assert.equal((script.match(/id: "(?:recognize|understand|examine|signal|decide)"/g)||[]).length,5);assert.match(script,/The Problem/);assert.match(script,/How It Works/);assert.match(script,/Start a Conversation/);assert.match(script,/aria-current="step"/);assert.match(styles,/\.capacity-path-inner/);assert.match(styles,/\.capacity-path-next/);assert.match(styles,/\.nav-primary-action/)});

test("shared navigation recognizes Netlify extensionless public routes",async()=>{const script=await readFile(new URL("script.js",root),"utf8");assert.match(script,/pathSegment && !pathSegment\.includes\("\."\) \? `\$\{pathSegment\}\.html` : pathSegment/)});

test("selected executive concern transparently carries into journey and signal entry",async()=>{const[shared,journeyHtml,journey,assessment,styles]=await Promise.all(["script.js","platform-journey.html","platform-journey.js","capacity-signal-assessment-app.js","styles.css"].map(file=>readFile(new URL(file,root),"utf8")));assert.equal((shared.match(/^  (?:scaling|retention|decisions|change|coordination|leadership): \{/gm)||[]).length,6);assert.match(shared,/searchParams\.set\("concern", key\)/);assert.match(shared,/contextualHref/);assert.match(journeyHtml,/Why this journey is framed this way/);assert.match(journeyHtml,/does not change the fictional evidence, diagnostic method, or result/);assert.match(journey,/concern\.journeyTitle/);assert.match(journey,/evidence and outcome remain controlled/);assert.match(assessment,/preselected a demand driver to reduce setup/);assert.match(assessment,/does not change the 18 signals, score your concern, or predetermine the brief/);assert.match(assessment,/Use a different starting point/);assert.match(assessment,/form\.elements\.demandSource\.value\s*=\s*concern\.demandSource/);assert.match(styles,/\.context-handoff/)});

test("public brand system uses the shared midnight-navy and burnt-orange palette",async()=>{const[styles,journey,organization,brief,engine]=await Promise.all(["styles.css","platform-journey.css","organization-view.css","capacity-brief-example.css","flow-engine.js"].map(file=>readFile(new URL(file,root),"utf8")));assert.match(styles,/--midnight: #111c2e/);assert.match(styles,/--orange: #d45b31/);assert.match(styles,/--paper: #fffdf8/);assert.match(styles,/border-bottom: 4px solid var\(--orange\)/);assert.match(engine,/amber: \[212, 91, 49\]/);for(const source of[styles,journey,organization,brief])assert.doesNotMatch(source,/#a46b38|#2563eb|#1e3a5f|#142c2b|#b86d3d|--bronze/i)});
