import test from "node:test";import assert from "node:assert/strict";
import {createWorkspaceDiagnosticStewardSessionsHandler} from "../netlify/functions/workspace-diagnostic-steward-sessions.mjs";
import {validateCompleteStewardSession,validateScheduleStewardSession} from "../netlify/lib/workspace-diagnostic-steward-sessions.mjs";
import {WORKSPACE_ROLES} from "../workspace-authorization.js";
const workspaceId="11111111-1111-4111-8111-111111111111",diagnosticId="22222222-2222-4222-8222-222222222222",future=new Date(Date.now()+86400000).toISOString();
const auth=role=>async()=>({ok:true,value:{workspaceId,userId:"user-1",role}});const request=(method="GET",body)=>new Request(`https://example.com/api/workspace/diagnostic-steward-sessions?diagnosticId=${diagnosticId}`,{method,headers:{origin:"https://example.com",...(body?{"content-type":"application/json"}:{})},body:body?JSON.stringify(body):undefined});
test("sponsor schedules a configured governed session",async()=>{let received;const handler=createWorkspaceDiagnosticStewardSessionsHandler({authenticate:auth(WORKSPACE_ROLES.owner),list:async()=>[],schedule:async value=>{received=value;return{sessionType:"guidance",scheduledAt:future};},links:{guidance:"https://onecal.io/example",design:null,revelation:null}});assert.equal((await handler(request())).status,200);assert.equal((await handler(request("POST",{diagnosticId,sessionType:"guidance",scheduledAt:future}))).status,201);assert.equal(received.input.sessionType,"guidance");});
test("participant cannot schedule and unconfigured links fail closed",async()=>{const participant=createWorkspaceDiagnosticStewardSessionsHandler({authenticate:auth(WORKSPACE_ROLES.participant),links:{guidance:"https://onecal.io/example"}});assert.equal((await participant(request("POST",{diagnosticId,sessionType:"guidance",scheduledAt:future}))).status,403);const missing=createWorkspaceDiagnosticStewardSessionsHandler({authenticate:auth(WORKSPACE_ROLES.owner),links:{guidance:null}});assert.equal((await missing(request("POST",{diagnosticId,sessionType:"guidance",scheduledAt:future}))).status,503);});
test("session contracts are bounded and completion is explicit",()=>{assert.equal(validateScheduleStewardSession({diagnosticId,sessionType:"design",scheduledAt:future}).sessionType,"design");assert.equal(validateCompleteStewardSession({diagnosticId,sessionType:"design",completionNote:"The sponsor and steward completed perspective and protocol design decisions."}).sessionType,"design");assert.throws(()=>validateScheduleStewardSession({diagnosticId,sessionType:"other",scheduledAt:future}),/governed/);});
