import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

const root = new URL("../", import.meta.url);

async function source(path) {
  return readFile(new URL(path, root), "utf8");
}

test("workspace is private-indexed and presents the threshold privacy contract", async () => {
  const html = await source("workspace/index.html");
  assert.match(html, /name="robots" content="noindex, nofollow"/);
  assert.match(html, /Individual scores are never shown to workspace roles/);
  assert.match(html, /Results remain suppressed below five valid submissions/);
  assert.match(html, /Workspace participation is separate from research consent/);
});

test("local product preview serves the public category homepage", async () => {
  const server = await readFile(new URL("../scripts/workspace-dev-server.mjs", import.meta.url), "utf8");
  assert.match(server, /\["\/", \{ url: new URL\("\.\.\/index\.html"/);
  assert.match(server, /\["\/flow-engine\.js", \{ url: new URL\("\.\.\/flow-engine\.js"/);
});

test("local product preview routes the v2 Diagnostic Frame endpoint", async () => {
  const server = await source("scripts/workspace-dev-server.mjs");
  assert.match(server, /workspace-diagnostic-frame-v2\.mjs/);
  assert.match(server, /\/api\/workspace\/diagnostic-frame-v2/);
  assert.match(server, /workspaceDiagnosticFrameV2/);
});

test("workspace browser uses server configuration and minimized session endpoints", async () => {
  const script = await source("workspace/workspace.js");
  const server = await source("scripts/workspace-dev-server.mjs");
  assert.match(script, /fetch\("\/api\/workspace\/config"/);
  assert.match(script, /fetch\("\/api\/workspace\/session"/);
  assert.match(script, /workspaceRequest\("\/api\/workspace\/rounds"/);
  assert.match(script, /workspaceRequest\("\/api\/workspace\/diagnostics"/);
  assert.match(script, /workspaceRequest\("\/api\/workspace\/diagnostic-context"/);
  assert.match(server, /import workspaceDiagnostics/);
  assert.match(server, /"\/api\/workspace\/diagnostics"/);
  assert.match(server, /import workspaceDiagnosticContext/);
  assert.match(server, /"\/api\/workspace\/diagnostic-context"/);
  assert.match(server, /workspace-diagnostic-frame-v2\.mjs/);
  assert.match(server, /"\/api\/workspace\/diagnostic-frame-v2"/);
  assert.match(server, /workspace-diagnostic-protocol-v2\.mjs/);
  assert.match(server, /"\/api\/workspace\/diagnostic-protocol-v2"/);
  assert.match(server, /import workspaceDiagnosticParticipants/);
  assert.match(server, /"\/api\/workspace\/diagnostic-participants"/);
  assert.match(server, /import workspaceDiagnosticProtocol/);
  assert.match(server, /"\/api\/workspace\/diagnostic-protocol"/);
  assert.match(server, /import workspaceDiagnosticInvitations/);
  assert.match(server, /"\/api\/workspace\/diagnostic-invitations"/);
  assert.match(server, /import workspaceDiagnosticParticipation/);
  assert.match(server, /"\/api\/workspace\/diagnostic-participation"/);
  assert.match(server, /import workspaceDiagnosticInterview/);
  assert.match(server, /"\/api\/workspace\/diagnostic-interview"/);
  assert.match(server, /"\/api\/workspace\/diagnostic-interview-v2"/);
  assert.match(script, /currentParticipation\.interviewVersion==="2\.0\.0"/);
  assert.match(script, /\/api\/workspace\/diagnostic-interview-v2/);
  assert.match(server, /"\/api\/workspace\/diagnostic-evidence-review"/);
  assert.match(server, /"\/api\/workspace\/diagnostic-evidence-preparation"/);
  assert.match(server, /"\/api\/workspace\/diagnostic-synthesis"/);
  assert.match(server, /"\/api\/workspace\/diagnostic-leadership-validation"/);
  assert.match(server, /"\/api\/workspace\/diagnostic-intervention"/);
  assert.match(server, /"\/api\/workspace\/diagnostic-intervention-acceptance"/);
  assert.match(server, /"\/api\/workspace\/capacity-operating-brief"/);
  assert.match(server, /"\/api\/workspace\/capacity-brief-evidence"/);
  assert.match(server, /"\/api\/workspace\/capacity-brief-reviews"/);
  assert.match(server, /"\/api\/workspace\/diagnostic-reassessment"/);
  assert.match(server, /"\/api\/workspace\/diagnostic-reassessment-comparison"/);
  assert.match(server, /"\/api\/workspace\/commerce-checkout"/);
  assert.match(server, /"\/api\/commerce\/stripe-webhook"/);
  assert.match(script, /workspaceRequest\("\/api\/workspace\/invitations"/);
  assert.match(script, /workspaceRequest\("\/api\/workspace\/participation"/);
  assert.match(script, /\/api\/workspace\/results\?roundId=/);
  assert.doesNotMatch(script, /CLERK_SECRET_KEY|NEON_DATABASE_URL|workspaceId|organizationId|userId/);
  assert.match(script, /This local workspace server is out of date/);
});

test("workspace keeps assessment collection separate from paid diagnostic engagement", async () => {
  const html = await source("workspace/index.html");
  const script = await source("workspace/workspace.js");
  const operationsScript = await source("workspace/operations.js");
  assert.match(html, /Organizational Capacity Diagnostic · Executive sponsor view/);
  assert.match(html, /This is separate from the lightweight assessment/);
  assert.match(html, /Senger Advisory establishes the engagement, route, and entitlement in Platform Operations/);
  assert.doesNotMatch(html, /data-create-diagnostic/);
  assert.doesNotMatch(script, /method:\s*"POST"[\s\S]{0,300}\/api\/workspace\/diagnostics/);
  assert.match(script, /Payment and access pending/);
  assert.match(script, /No human review required/);
  assert.match(html, /Approve the Diagnostic Context Brief/);
  assert.match(html, /not a predetermined diagnosis/);
  assert.match(html, /One per line, up to twelve/);
  assert.match(script, /Participant design is now the next governed step/);
  assert.match(html, /Design for coverage, not convenience/);
  assert.match(html, /There is no fixed qualitative minimum/);
  assert.match(html, /Identity is added only after this plan is approved/);
  assert.match(script, /workspaceRequest\("\/api\/workspace\/diagnostic-participants"/);
  assert.match(script, /Coverage gaps need a design change or an explicit acceptance reason/);
  assert.match(html, /Review the 15-question protocol/);
  assert.match(html, /Every participant receives this same contextualized core protocol/);
  assert.match(script, /workspaceRequest\("\/api\/workspace\/diagnostic-protocol"/);
  assert.match(script, /Validating coverage and approving the common protocol/);
  assert.match(html, /Assign approved perspective slots/);
  assert.match(html, /remains separate from confidential interview content/);
  assert.match(script, /workspaceRequest\("\/api\/workspace\/diagnostic-invitations"/);
  assert.match(html, /data-diagnostic-collection-progress/);
  assert.match(script, /Client sponsor · POC workspace/);
  assert.match(script, /Responses submitted/);
  assert.doesNotMatch(script, /slot\.interviewAnswers|slot\.encryptedResponse/);
  assert.match(script, /workspaceRequest\("\/api\/workspace\/diagnostic-participation"/);
  assert.match(operationsScript, /\/api\/operations\/diagnostic-v2-activation/);
  assert.match(script, /Accept the diagnostic privacy notice/);
  assert.match(html, /Save private draft/);
  assert.match(html, /Submit diagnostic interview/);
  assert.match(script, /"\/api\/workspace\/diagnostic-interview-v2":"\/api\/workspace\/diagnostic-interview"/);
  assert.match(script, /Your confidential diagnostic interview is complete\./);
  assert.match(script, /Submission confirmed\. No further action is required right now\./);
  assert.match(script, /Saving encrypted draft/);
  assert.match(script, /Evidence-depth review requested/);
  assert.match(script, /data-follow-up-answer/);
  assert.match(script, /setTimeout\(\(\)=>saveInterviewDraft\(\),1200\)/);
  assert.match(script, /currentParticipation\?\.kind === "diagnostic"/);
  assert.match(script, /beforeunload/);
  assert.doesNotMatch(script, /diagnostic\.individualAnswers|diagnostic\.participantIdentity/);
});

test("Platform Operations is separate, allowlisted, and excludes participant content",async()=>{
  const html=await source("workspace/operations.html"),script=await source("workspace/operations.js"),server=await source("scripts/workspace-dev-server.mjs"),auth=await source("netlify/lib/platform-operations-auth.mjs");
  assert.match(html,/Senger Advisory authority/);
  assert.match(html,/Participant identity, responses, excerpts, and individual scores never appear here/);
  assert.match(html,/Create diagnostic engagement/);
  assert.match(script,/\/api\/operations\/overview/);
  assert.match(script,/\/api\/operations\/diagnostics/);
  assert.match(auth,/PLATFORM_OPERATOR_USER_IDS/);
  assert.match(auth,/authority: "platform-operator"/);
  assert.match(server,/platformOperationsOverview/);
  assert.match(server,/platformOperationsDiagnostics/);
  assert.doesNotMatch(script,/participantIdentity|answerText|encrypted_response_payload|individualScores/);
});

test("participant entry requires a privacy acknowledgement before assessment navigation", async () => {
  const html = await source("workspace/index.html");
  const script = await source("workspace/workspace.js");
  assert.match(html, /I understand how my workspace assessment will be used/);
  assert.match(html, /Begin private assessment/);
  assert.match(script, /noticeVersion:\s*currentParticipation\.noticeVersion/);
  assert.match(script, /workspaceRound/);
});

test("workspace assessment submits aggregate scores without individual answers or identity", async () => {
  const html = await source("assessment.html");
  const script = await source("assessment.js");
  assert.match(html, /Individual answers remain in this browser/);
  assert.match(script, /fetch\("\/api\/workspace\/submission"/);
  assert.match(script, /domainScores:/);
  assert.match(script, /nextAction\.textContent = "Return to workspace"/);
  assert.doesNotMatch(script, /workspaceSubmission\(\)[\s\S]{0,700}(responses|emailAddress|userId)/);
});

test("owner collection setup presents dates and the fixed privacy threshold", async () => {
  const html = await source("workspace/index.html");
  const script = await source("workspace/workspace.js");
  assert.match(html, /Create a collection round/);
  assert.match(html, /Participation opens/);
  assert.match(html, /Participation closes/);
  assert.match(html, /valid submissions required before shared results appear/);
  assert.match(html, /Submission count is not connected to the invitation list/);
  assert.match(html, /Draft reminders for nonrespondents/);
  assert.match(script, /Accepted · not started/);
  assert.match(script, /Assessment started/);
  assert.match(script, /Submitted/);
  assert.match(script, /mailto:/);
  assert.match(html, /Shared constraint hypothesis/);
  assert.match(html, /not a benchmark, consensus score, or measure of individual performance/);
  assert.match(script, /Decision ownership and closure may not be scaling/);
  assert.match(html, /Turn the signal into a testable commitment/);
  assert.match(html, /Responsible owner/);
  assert.match(script, /\/api\/workspace\/action-cycles/);
  assert.match(script, /Review observation/);
  assert.match(script, /method:\s*"PATCH"/);
  assert.match(script, /review overdue/);
  assert.match(script, /Create linked follow-up draft/);
  assert.match(script, /action:\s*"close"/);
  assert.match(script, /\/api\/workspace\/comparison\?roundId=/);
  assert.match(html, /What changed between collection rounds/);
});

test("workspace authentication always returns to the workspace route", async () => {
  const script = await source("workspace/workspace.js");
  assert.match(script, /forceRedirectUrl:\s*"\/workspace\/"/);
  assert.match(script, /signUpForceRedirectUrl:\s*"\/workspace\/"/);
  assert.doesNotMatch(script, /afterSignInUrl|afterSignUpUrl/);
});

test("workspace has a route-only Clerk CSP and authentication return fallback", async () => {
  const config = await source("netlify.toml");
  assert.match(config, /for = "\/workspace\/\*"/);
  assert.match(config, /https:\/\/\*\.clerk\.accounts\.dev/);
  assert.match(config, /https:\/\/challenges\.cloudflare\.com/);
  assert.match(config, /from = "\/workspace\/\*"\s+to = "\/workspace\/index\.html"\s+status = 200/);
});

test("workspace remains excluded from search crawling", async () => {
  const robots = await source("robots.txt");
  assert.match(robots, /Disallow: \/workspace\//);
});

test("advisor console is separate, assignment-scoped, and excludes raw interview fields", async () => {
  const html = await readFile(new URL("../workspace/advisor.html", import.meta.url), "utf8");
  const advisor = await readFile(new URL("../workspace/advisor.js", import.meta.url), "utf8");
  assert.match(html, /Advisor Operating Console/);
  assert.match(html, /Frame and test organizational capacity/);
  assert.match(html, /active, time-bounded advisor assignment/);
  assert.match(advisor, /diagnostic-advisor-assignments/);
  assert.match(html, /Define capacity for what/);
  assert.match(html, /Complexity Profile/);
  assert.match(html, /evidence hypothesis—not a sponsor conclusion/);
  assert.match(advisor, /diagnostic-frame-v2/);
  assert.match(advisor, /current-and-anticipated/);
  assert.match(advisor, /The live v1 diagnostic remains unchanged/);
  assert.match(html, /Evidence Protocol v2/);
  assert.match(html, /shared inquiry/);
  assert.match(html, /Adaptive Capacity remains a research observation/);
  assert.match(advisor, /diagnostic-protocol-v2/);
  assert.match(advisor, /evidenceLayerId/);
  assert.match(advisor, /Participant collection remains on v1/);
  assert.match(advisor, /diagnostic-evidence-preparation/);
  assert.match(advisor, /diagnostic-evidence-review/);
  assert.match(advisor, /diagnostic-synthesis/);
  assert.match(html, /Only advisor-approved de-identified evidence enters this draft/);
  assert.match(html, /Advisor validation/);
  assert.match(html, /It does not release the finding or replace client leadership validation/);
  assert.match(advisor, /Competing explanations/);
  assert.match(advisor, /Blind spots/);
  assert.match(advisor, /Confidence basis/);
  assert.match(advisor, /method:"PATCH"/);
  assert.match(html, /Governed intervention design/);
  assert.match(advisor, /Leadership validation must be accepted before intervention design becomes available/);
  assert.match(html, /Platform-guided intervention/);
  assert.match(html, /Advisor-guided intervention/);
  assert.match(html, /Accountable commitment/);
  assert.match(html, /Observed operating change/);
  assert.match(html, /Reassessed capacity change/);
  assert.match(html, /Create governed proposal/);
  assert.match(advisor, /evidenceClass:"delivery"/);
  assert.match(advisor, /evidenceClass:"operating-change"/);
  assert.match(advisor, /evidenceClass:"capacity-change"/);
  assert.doesNotMatch(advisor, /answerText|encrypted_response_payload|sourceInterviewId/);
  assert.match(advisor, /Mechanisms implicated — not scored/);
  assert.match(advisor, /Boundary conditions/);
});

test("client sponsor receives only a confidentiality-gated governed finding", async () => {
  const html = await source("workspace/index.html");
  const script = await source("workspace/workspace.js");
  const advisorHtml = await source("workspace/advisor.html");
  const advisorScript = await source("workspace/advisor.js");
  assert.match(html, /Review the governed organizational finding/);
  assert.match(html, /Participant identity, raw responses, evidence excerpts, and advisor notes remain excluded/);
  assert.match(script, /diagnostic-leadership-validation/);
  assert.match(script, /No participant-level or organizational finding data has been released/);
  assert.match(html, /Does this finding reflect the organizational condition/);
  assert.match(html, /material objection that must be resolved/);
  assert.match(script, /Finding accepted\. Intervention design is the next governed gate/);
  assert.match(html, /Review the proposed operating intervention/);
  assert.match(html, /I accept the proposed intervention scope/);
  assert.match(html, /I accept the commercial terms/);
  assert.match(script, /Payment and intervention access must be verified/);
  assert.match(script, /Capacity Operating Brief activation is the next gate/);
  assert.match(html, /Keep the constraint, intervention, and evidence in view/);
  assert.match(html, /not a generic dashboard/);
  assert.match(html, /Activate Capacity Operating Brief/);
  assert.match(script, /Current diagnosed constraint/);
  assert.match(script, /Uncertainty kept visible/);
  assert.doesNotMatch(script, /supportingEvidenceIds|participantIdentity|rawResponse/);
  assert.match(html, /Record what is observed—not what the intervention is assumed to have caused/);
  assert.match(html, /Intervention delivery/);
  assert.match(html, /Observed operating change/);
  assert.match(html, /Reassessed capacity change/);
  assert.match(html, /Record evidence observation/);
  assert.match(html, /Use the evidence to continue, adjust, escalate, stop, or begin reassessment/);
  assert.match(html, /Record intervention review/);
  assert.match(script, /evidenceAssessment/);
  assert.match(html, /Begin reassessment/);
  assert.match(html, /Repeat the diagnostic without weakening the comparison/);
  assert.match(html, /Comparison is unavailable until a qualifying reassessment is complete/);
  assert.match(script, /loadReassessment/);
  assert.match(script, /Plan governed reassessment/);
  assert.match(script, /Open reassessment collection/);
  assert.match(script, /Participant identities and response content are not copied/);
  assert.match(html, /data-reassessment-comparison/);
  assert.match(script, /Governed comparison/);
  assert.match(advisorHtml, /Release only evidence-traceable change/);
  assert.match(advisorScript, /No causal claim was created/);
  assert.match(script, /Complete payment/);
  assert.match(script, /commerce-checkout/);
  assert.match(html, /Pay for intervention/);
  assert.match(html, /Learning Path/);
  assert.match(html, /Completion records implementation/);
  assert.match(script, /capacity-brief-learning/);
  assert.match(html, /30 \/ 60 \/ 90-day Action Path/);
  assert.match(script, /capacity-brief-action-path/);
  assert.match(html, /Guided check-ins/);
  assert.match(script, /capacity-brief-check-ins/);
  assert.match(html, /What needs attention now/);
  assert.match(script, /capacity-brief-attention/);
  assert.match(html, /Escalate to advisor support/);
  assert.match(script, /intervention-advisor-escalation/);
  assert.match(advisorHtml, /Advisor support queue/);
  assert.match(advisorScript, /advisor-escalation-queue/);
  assert.match(html, /Decision History/);
  assert.match(script, /capacity-brief-decision-history/);
  assert.match(html, /Platform-guided setup/);
  assert.match(script, /capacity-brief-guided-plan/);
  assert.match(html, /POC checkpoint/);
  assert.match(html, /Optional product feedback/);
  assert.match(script, /workspace\/poc-feedback/);
  assert.match(advisorHtml, /POC scorecard/);
  assert.match(advisorScript, /workspace\/poc-scorecard/);
  assert.match(advisorHtml, /POC cohort decision/);
  assert.match(advisorScript, /workspace\/poc-cohort-decisions/);
  assert.match(advisorHtml, /POC change ledger/);
  assert.match(advisorScript, /workspace\/poc-change-candidates/);
  assert.match(script, /currentClerkContextKey\(\) === clerkContextKey/);
  assert.match(script, /workspaceRenderPromise/);
  assert.match(script, /beginDiagnosticCheckout\(selectedDiagnosticId,"intervention"\)/);
  assert.doesNotMatch(script, /supportingEvidenceIds|weakeningEvidenceIds|advisorReviewNote/);
});

test("guided presenter demo is fictional, resettable, and disconnected from live records", async () => {
  const html = await source("workspace/presenter-demo.html");
  const script = await source("workspace/presenter-demo.js");
  const server = await source("scripts/workspace-dev-server.mjs");
  assert.match(html, /Private guided demo/);
  assert.match(html, /fictional organization/i);
  assert.match(html, /Nothing is saved, submitted, or connected to a live client workspace/);
  assert.match(html, /data-role="sponsor"/);
  assert.match(html, /data-role="participant"/);
  assert.match(script, /label:"Assessment"/);
  assert.match(script, /label:"Choose diagnostic"/);
  assert.match(script, /label:"Six sponsor prompts"/);
  assert.match(script, /label:"Invite the cohort"/);
  assert.match(script, /label:"Participant experience"/);
  assert.match(script, /label:"Privacy threshold"/);
  assert.match(script, /label:"De-identify & synthesize"/);
  assert.match(script, /label:"Results & intervention"/);
  assert.match(script, /Capacity Operating Brief/);
  assert.match(script, /data-brief-view/);
  assert.match(script, /data-intake/);
  assert.match(script, /data-cohort-range/);
  assert.match(script, /data-add-submission/);
  assert.match(script, /Organizational results remain hidden/);
  assert.match(script, /de-identified and disclosure-reviewed/);
  assert.match(script, /Separate from this controlled demo/);
  assert.doesNotMatch(script, /pressure test|Pressure Test/);
  assert.match(script, /Your confidential diagnostic interview is complete/);
  assert.match(script, /Question 6 of 15/);
  assert.doesNotMatch(script, /fetch\(|workspaceRequest\(|localStorage|sessionStorage/);
  assert.match(server, /"\/workspace\/presenter-demo\.html"/);
});
