[build]
  publish = "."

[[redirects]]
  from = "/model"
  to = "/framework.html"
  status = 301

[[redirects]]
  from = "/framework"
  to = "/framework.html"
  status = 301

[[redirects]]
  from = "/diagnostic"
  to = "/diagnostic.html"
  status = 301

[[redirects]]
  from = "/signs"
  to = "/signs.html"
  status = 301
