const elements={status:document.querySelector("[data-operations-status]"),signIn:document.querySelector("[data-operations-sign-in]"),console:document.querySelector("[data-operations-console]"),signOut:document.querySelector("[data-sign-out]"),workspaceLabel:document.querySelector("[data-workspace-label]"),workspaceStatus:document.querySelector("[data-workspace-status]"),summary:document.querySelector("[data-operations-summary]"),form:document.querySelector("[data-diagnostic-form]"),message:document.querySelector("[data-diagnostic-message]"),list:document.querySelector("[data-diagnostic-list]"),assignmentForm:document.querySelector("[data-advisor-assignment-form]"),assignmentDiagnostic:document.querySelector("[data-assignment-diagnostic]"),assignmentMessage:document.querySelector("[data-advisor-assignment-message]"),assignmentList:document.querySelector("[data-advisor-assignment-list]")};
let clerk;
async function request(path,options={}){const response=await fetch(path,{credentials:"same-origin",headers:{Accept:"application/json",...(options.body?{"Content-Type":"application/json"}:{})},...options,body:options.body?JSON.stringify(options.body):undefined});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error||"The platform operation could not be completed.");return payload;}
function script(src,key){return new Promise((resolve,reject)=>{const value=document.createElement("script");value.async=true;value.crossOrigin="anonymous";if(key)value.dataset.clerkPublishableKey=key;value.src=src;value.onload=resolve;value.onerror=reject;document.head.append(value);});}
async function activeOrganization(){if(clerk.organization)return true;const memberships=clerk.user?.organizationMemberships||[];if(memberships.length!==1)return false;await clerk.setActive({organization:memberships[0].organization.id});return Boolean(clerk.organization);}
function metric(value,label){const card=document.createElement("article"),number=document.createElement("strong"),caption=document.createElement("span");number.textContent=value;caption.textContent=label;card.append(number,caption);return card;}
function render(data){elements.workspaceLabel.textContent=data.workspace.label;elements.workspaceStatus.textContent=data.workspace.status;elements.summary.replaceChildren(metric(data.summary.diagnostics,"diagnostic records"),metric(data.summary.activePocs,"active POCs"),metric(data.summary.participantsCompleted,"completed interviews"),metric(data.summary.itemsNeedingReview,"evidence items awaiting review"));elements.assignmentDiagnostic.replaceChildren();elements.list.replaceChildren();for(const value of data.diagnostics){const option=document.createElement("option");option.value=value.diagnosticId;option.textContent=`${value.route==="automated"?"Automated written":"Advisor-led"} · ${value.state}`;elements.assignmentDiagnostic.append(option);const card=document.createElement("article");card.className="operations-card";const identity=document.createElement("div");identity.innerHTML=`<h3>${option.textContent}</h3><p>${value.entitlementType.toUpperCase()} · ${value.entitlementStatus}</p>`;const participation=document.createElement("div");participation.innerHTML=`<strong>${value.participation.completed}/${value.participation.assigned}</strong><span>interviews complete</span>`;const review=document.createElement("div");review.innerHTML=`<strong>${value.pendingEvidence}</strong><span>pending evidence</span>`;const advisors=document.createElement("div");advisors.innerHTML=`<strong>${value.activeAdvisors}</strong><span>active advisors</span>`;const learning=document.createElement("div");learning.innerHTML=`<strong>${value.feedbackCount} / ${value.changeCandidates}</strong><span>feedback / changes</span>`;card.append(identity,participation,review,advisors,learning);elements.list.append(card);}elements.assignmentForm.querySelector("button").disabled=!data.diagnostics.length;if(!data.diagnostics.length){const empty=document.createElement("p");empty.textContent="No diagnostic engagements have been created for this organization.";elements.list.append(empty);}}
async function loadAssignments(){const data=await request("/api/operations/advisor-assignments");elements.assignmentList.replaceChildren();for(const value of data.assignments.filter(item=>item.active)){const row=document.createElement("article"),detail=document.createElement("div"),button=document.createElement("button");row.className="operations-assignment";detail.innerHTML=`<strong>${value.advisorClerkUserId}</strong><p>${value.purpose} · Expires ${new Date(value.expiresAt).toLocaleString()}</p>`;button.type="button";button.textContent="Revoke";button.dataset.assignmentId=value.assignmentId;button.dataset.diagnosticId=value.diagnosticId;row.append(detail,button);elements.assignmentList.append(row);}if(!elements.assignmentList.children.length)elements.assignmentList.textContent="No active advisor assignments.";}
async function load(){const data=await request("/api/operations/overview");render(data);await loadAssignments();elements.console.hidden=false;elements.signOut.hidden=false;elements.status.textContent="Platform-operator authority confirmed. Client data remains tenant-bounded.";}
async function initialize(){try{const config=await request("/api/workspace/config");await script(config.clerkUiUrl);await script(config.clerkJsUrl,config.publishableKey);clerk=window.Clerk;await clerk.load({ui:{ClerkUI:window.__internal_ClerkUICtor}});if(!clerk.user){elements.status.textContent="Sign in with an authorized Senger Advisory account.";clerk.mountSignIn(elements.signIn,{fallbackRedirectUrl:"/workspace/operations.html"});return;}if(!(await activeOrganization()))throw new Error("Select a valid client organization before opening Platform Operations.");await load();}catch(error){elements.status.textContent=error.message;}}
elements.form.addEventListener("submit",async event=>{event.preventDefault();if(!elements.form.reportValidity())return;const button=elements.form.querySelector("button"),values=Object.fromEntries(new FormData(elements.form));button.disabled=true;elements.message.textContent="Creating the governed engagement and entitlement…";try{const data=await request("/api/operations/diagnostics",{method:"POST",body:values});elements.message.textContent=data.diagnostic.entitlementStatus==="active"?"POC engagement created. The sponsor can now complete the context brief.":"Paid engagement created with checkout pending.";await load();}catch(error){elements.message.textContent=error.message;}finally{button.disabled=false;}});
elements.assignmentForm.addEventListener("submit",async event=>{event.preventDefault();if(!elements.assignmentForm.reportValidity())return;const button=elements.assignmentForm.querySelector("button"),values=Object.fromEntries(new FormData(elements.assignmentForm));button.disabled=true;try{await request("/api/operations/advisor-assignments",{method:"POST",body:{action:"assign",...values,durationDays:Number(values.durationDays)}});elements.assignmentMessage.textContent="Advisor access assigned and recorded in the audit history.";await load();}catch(error){elements.assignmentMessage.textContent=error.message;}finally{button.disabled=false;}});
elements.assignmentList.addEventListener("click",async event=>{const button=event.target.closest("[data-assignment-id]");if(!button)return;const reason=window.prompt("Record why this advisor access is being revoked:");if(!reason)return;button.disabled=true;try{await request("/api/operations/advisor-assignments",{method:"POST",body:{action:"revoke",assignmentId:button.dataset.assignmentId,diagnosticId:button.dataset.diagnosticId,reason}});elements.assignmentMessage.textContent="Advisor access revoked immediately.";await load();}catch(error){elements.assignmentMessage.textContent=error.message;button.disabled=false;}});
elements.signOut.addEventListener("click",async()=>{await clerk.signOut({redirectUrl:"/workspace/operations.html"});});
initialize();
