const pressures={
  commercial:{label:"Growth & commercial performance",context:"Growth & commercial performance",decision:"What is constraining the organization’s ability to convert market opportunity into durable performance?",description:"Growth pressure is visible, but leadership cannot yet distinguish market, execution, or capacity constraints."},
  retention:{label:"Customer retention & experience",context:"Customer retention & experience",decision:"How should leadership protect retention without sacrificing the platform strategy?",description:"Renewal risk is visible, but the organizational mechanism remains disputed."},
  execution:{label:"Execution & delivery",context:"Execution & delivery",decision:"What is preventing strategy from moving cleanly into dependable delivery?",description:"Work is moving, but handoffs, exceptions, and escalation are consuming capacity."},
  scaling:{label:"Scaling complexity",context:"Scaling complexity",decision:"What must change before growth adds more complexity than capacity?",description:"The practices that enabled early growth are beginning to constrain the next stage."},
  change:{label:"AI adoption & change",context:"AI adoption & change",decision:"What must the organization be able to absorb before accelerating change?",description:"Technology opportunity is outpacing decision clarity, coordination, and management capacity."},
  leadership:{label:"Leadership & coordination",context:"Leadership & coordination",decision:"Where must leadership clarity and coordination improve for execution to move without constant escalation?",description:"Leadership effort is high, but authority, accountability, and coordination are not producing consistent movement."}
};

const scopes={
  organization:{label:"Organization-wide",context:"Organization-wide",decision:"across the organization",description:"The inquiry examines how the full organizational system shapes the decision."},
  function:{label:"One function or business unit",context:"Function or business unit",decision:"within the selected function or business unit",description:"The inquiry goes deep within a bounded segment while retaining its connection to the wider system."},
  crossFunctional:{label:"A cross-functional system",context:"Cross-functional system",decision:"across the functions responsible for the outcome",description:"The inquiry follows work across the boundaries where ownership, information, and handoffs interact."}
};

const perspectiveViews={
  sales:{role:"Frontline Sales",level:"Individual contributor",observes:"Customer promises, objection patterns, commercial pressure, and where deal exceptions originate."},
  product:{role:"Product Manager",level:"Cross-functional manager",observes:"Exception demand, roadmap tradeoffs, priority changes, and the cost of switching attention."},
  success:{role:"Customer Success Director",level:"Functional leader",observes:"Handoff quality, support readiness, renewal exposure, and when customer risk becomes visible."},
  engineering:{role:"Engineering Manager",level:"Delivery leader",observes:"Capacity diversion, implementation consequences, technical debt, and recurring escalation work."},
  regional:{role:"Regional Operations Lead",level:"Distributed execution",observes:"Where centralized decisions lose context and how operating changes land outside headquarters."}
};

const reasoningViews={
  escalation:{label:"Decision escalation",type:"Converging mechanism cluster",statement:"Custom exceptions repeatedly move upward because operating authority has not caught up with the platform strategy.",vantages:["Frontline Sales","Product Manager","Engineering Manager"],strengthens:["Exception thresholds are unclear below the executive team.","The same tradeoff is repeatedly treated as a novel case."],weakens:"Evidence that delegated thresholds already resolve comparable exceptions without escalation.",change:"If escalation persists after clear thresholds are introduced, information latency becomes the stronger explanation.",status:"Strong convergence"},
  information:{label:"Late customer intelligence",type:"Competing mechanism cluster",statement:"Customer-risk information may reach decision makers too late to govern commercial and product tradeoffs.",vantages:["Customer Success Director","Frontline Sales","Product Manager"],strengthens:["Renewal exposure surfaces after custom commitments are made.","Support impact is not visible at proposal approval."],weakens:"Several escalations occurred even when customer-risk information was available early.",change:"If earlier customer signals materially reduce exceptions, information flow—not authority—is likely primary.",status:"Material counterpoint"},
  compensation:{label:"Compensating coordination",type:"Reinforcing mechanism cluster",statement:"Managers are using meetings, personal relationships, and manual follow-up to compensate for unreliable operating boundaries.",vantages:["Engineering Manager","Regional Operations Lead","Customer Success Director"],strengthens:["Handoffs succeed when particular individuals intervene.","Regional teams create parallel coordination routines."],weakens:"Some protected workflows move reliably without additional coordination effort.",change:"If coordination load remains high after decision rights improve, handoff design requires separate treatment.",status:"Moderate convergence"}
};

const phases=[
  {id:"reveal",label:"Reveal",sub:"Decision-ready clarity",status:"Brief released",kicker:"Executive revelation",title:"The organizational system comes into view.",summary:"A protected Capacity Brief reframes the decision and identifies what leadership should test first.",objective:"Create the first aha moment before explaining the process.",question:"If this were your organization, which part of this finding would change the executive conversation?",proof:"The Brief separates evidence, inference, uncertainty, and intervention direction in one governed artifact.",transition:"Now let me show you why leadership can trust what it is seeing."},
  {id:"synthesize",label:"Synthesize",sub:"Evidence becomes insight",status:"Synthesis approved",kicker:"Protected synthesis",title:"Evidence becomes an organizational finding—not a collection of opinions.",summary:"Threshold-qualified evidence is de-identified, reviewed, tested against counterpoints, and governed before release.",objective:"Demonstrate methodological depth without exposing the proprietary reasoning chain.",question:"Would your leaders trust a finding more if the system showed what could disconfirm it?",proof:"The platform retains competing explanations and makes uncertainty explicit before recommending action.",transition:"The synthesis is possible only because collection protects candor by design."},
  {id:"collect",label:"Collect",sub:"Confidential perspectives",status:"Threshold met",kicker:"Confidential collection",title:"Different vantage points reveal how work actually moves.",summary:"Participants complete one contextual 18-question protocol; sponsors see aggregate progress, never individual content.",objective:"Make confidentiality tangible through product behavior rather than reassurance alone.",question:"Who sees a consequential part of execution that the executive team may not see?",proof:"Below five completions, organizational results remain locked. Identity and response content stay separated.",transition:"Those perspectives were not chosen casually; they were deliberately designed."},
  {id:"design",label:"Design",sub:"Inquiry and perspectives",status:"Protocol approved",kicker:"Governed inquiry design",title:"The diagnostic is contextual without becoming sponsor-led.",summary:"Six sponsor prompts and an identity-free perspective plan shape a common protocol that the sponsor may approve or reason-code for reframing.",objective:"Show how the inquiry becomes specific while resisting confirmation bias.",question:"Which perspective would be most likely to challenge the sponsor’s current explanation?",proof:"The sponsor cannot add leading questions or freely rewrite the protocol. Every participant receives the same core inquiry.",transition:"All of this begins by bounding one consequential executive decision."},
  {id:"frame",label:"Frame",sub:"Pressure and decision",status:"Guidance required",kicker:"Guided diagnostic start",title:"A broad concern becomes one decision the organization must inform.",summary:"A steward helps the sponsor distinguish symptoms from the execution demand before anyone is invited.",objective:"Connect the prospect’s pressure to a bounded diagnostic engagement.",question:"What decision is important enough that leadership should not rely on its current explanation alone?",proof:"The POC begins with six plain-language prompts and a required Guidance Session—not an unguided survey.",transition:"From here, the sponsor designs whose view of the system is needed."}
];

const surfaces={
  reveal:{
    sponsor:`<div class="capacity-brief"><div class="brief-mast"><div><span>Executive Capacity Brief</span><strong>Aetheris Dynamics</strong></div><b>Released for Revelation</b></div><div class="finding-hero"><span>Governing finding</span><h3>Commercial strategy and daily decision governance are pulling organizational capacity in opposite directions.</h3><p>Custom exceptions repeatedly move upward, redirect engineering attention, and surface customer risk too late.</p></div><div class="evidence-row"><button data-inspect="convergence" class="active"><span>Evidence convergence</span><strong>3 reinforcing patterns</strong></button><button data-inspect="counterpoint"><span>Counterpoint retained</span><strong>1 competing explanation</strong></button><button data-inspect="confidence"><span>Interpretive confidence</span><strong>Moderate</strong></button></div><div class="decision-reframe"><span>Decision reframed</span><p><del>Should we cap custom deals?</del></p><strong>What rights, information, and operating boundaries must change so platform strategy governs daily work?</strong></div><div class="direction-stack"><header><span>Evidence-informed directions</span><b>Decision support—not probability of success</b></header><article class="recommended"><i>01</i><div><strong>Decision-rights and accountability redesign</strong><p>Recommended first · observable signal in 30–45 days</p></div><b>88</b></article><article><i>02</i><div><strong>Shared operating intelligence protocol</strong><p>Alternative direction</p></div><b>76</b></article><article><i>03</i><div><strong>Cross-boundary coordination redesign</strong><p>Alternative direction</p></div><b>64</b></article></div></div>`,
    participant:`<div class="participant-closure"><span>✓</span><h3>Your confidential interview contributed to an organizational view.</h3><p>You will not receive findings or see other responses. Your identity remains separated from interview content throughout evidence review and synthesis.</p><div><strong>What the sponsor receives</strong><span>A de-identified organizational Brief after threshold and review</span></div><div><strong>What the sponsor never receives</strong><span>Your answers, excerpts, individual score, or submission status tied to your name</span></div></div>`,
    steward:`<div class="dual-output"><article><span>Sponsor-facing</span><h3>Executive Capacity Brief</h3><ul><li>Finding and business exposure</li><li>Evidence pattern and uncertainty</li><li>Three weighted directions</li><li>Activation boundary</li></ul><b>Released deliberately</b></article><article class="private-output"><span>Steward only</span><h3>Revelation Guide</h3><ul><li>Evidence trace and mechanics</li><li>Science and psychology</li><li>Cost-of-inaction discussion</li><li>Questions, cautions, and talk track</li></ul><b>Never sponsor-visible</b></article></div>`
  },
  synthesize:{
    sponsor:`<div class="sponsor-synthesis"><header><div><span>Protected synthesis · sponsor view</span><strong>Your diagnostic is becoming a governed organizational finding.</strong></div><b>Evidence review in progress</b></header><div class="synthesis-receipt"><article><strong>5</strong><span>Confidential perspectives accepted</span></article><article><strong>18</strong><span>Common contextual questions completed</span></article><article><strong>✓</strong><span>Minimum confidentiality threshold met</span></article></div><section class="synthesis-activity"><div class="activity-copy"><span>What the platform is doing now</span><h3>Testing explanations—not summarizing opinions.</h3><p>Protected evidence is being reviewed across vantage points, checked for disclosure risk, compared against competing explanations, and tested for uncertainty before any finding can be approved.</p></div><div class="activity-orbit" aria-label="Protected synthesis activities"><i class="center">Governed<br>finding</i><span style="--angle:0deg">De-identify</span><span style="--angle:72deg">Converge</span><span style="--angle:144deg">Challenge</span><span style="--angle:216deg">Qualify</span><span style="--angle:288deg">Approve</span></div></section><div class="sponsor-boundaries"><article><span>Visible now</span><strong>Progress, completed governance gates, and the next required action</strong><p>You can verify that the process is moving without seeing premature conclusions.</p></article><article class="protected"><span>Protected until Revelation</span><strong>Themes, evidence, excerpts, hypotheses, scores, and preliminary findings</strong><p>These remain inaccessible until review is complete and the steward deliberately releases the Brief.</p></article></div><div class="release-gates"><header><span>Release readiness</span><strong>3 of 5 gates complete</strong></header><div><i class="done"><b>✓</b><span>Collection complete</span></i><i class="done"><b>✓</b><span>Threshold met</span></i><i class="done"><b>✓</b><span>Disclosure controls</span></i><i class="active"><b>4</b><span>Synthesis approval</span></i><i><b>5</b><span>Steward release</span></i></div><footer><span>Next</span><strong>The steward approves the Executive Capacity Brief and private Revelation Guide separately.</strong></footer></div></div>`,
    participant:`<div class="participant-closure"><span>✓</span><h3>Your part is complete.</h3><p>Your submitted response has entered a protected process. It cannot be reopened by the sponsor or associated with your identity in organizational findings.</p></div>`,
    steward:`<div class="reasoning-room"><header><div><span>Protected reasoning room</span><strong>Test explanations before producing a finding.</strong></div><b>Threshold qualified · steward governed</b></header><div class="reasoning-flow"><span class="done">Observed signals</span><i>→</i><span class="active">Mechanism hypotheses</span><i>→</i><span>Counterevidence</span><i>→</i><span>Uncertainty</span><i>→</i><span>Governing finding</span></div><div class="reasoning-body"><nav aria-label="Inspect synthesis mechanism clusters">${Object.entries(reasoningViews).map(([id,item],index)=>`<button type="button" data-reasoning="${id}" ${index===0?'class="active"':''}><span>${item.type}</span><strong>${item.label}</strong><small>${item.status}</small></button>`).join("")}</nav><section class="reasoning-panel" data-reasoning-panel></section></div><div class="hypothesis-comparison"><article class="leading"><span>Leading explanation</span><strong>Authority does not match strategy.</strong><div><i style="--weight:82%"></i></div><small>Best current fit—not a probability of truth</small></article><article><span>Competing explanation</span><strong>Customer intelligence arrives too late.</strong><div><i style="--weight:61%"></i></div><small>Material and explicitly retained</small></article></div><div class="governed-finding"><span>Governed progression</span><p>Observed signals <i>→</i> mechanism hypothesis <i>→</i> counterevidence <i>→</i> uncertainty <i>→</i> governing finding</p><strong>Commercial strategy and daily decision governance are pulling organizational capacity in opposite directions.</strong></div></div>`
  },
  collect:{
    sponsor:`<div class="collection-board"><header><div><span>Collection round</span><strong>7 invited perspectives</strong></div><b>Threshold met</b></header><section class="perspective-constellation"><div class="constellation-heading"><div><span>Illustrative perspectives · this fictional engagement</span><strong>Different vantage points reveal different parts of the same system.</strong></div><small>These are not prescribed roles for a real diagnostic.</small></div><div class="constellation-body"><nav aria-label="Explore illustrative vantage points">${Object.entries(perspectiveViews).map(([id,item],index)=>`<button type="button" data-perspective="${id}" ${index===0?'class="active"':''}><i></i><span>${item.role}</span><small>${item.level}</small></button>`).join("")}</nav><div class="vantage-card" data-perspective-panel></div></div></section><div class="collection-number"><strong>5</strong><span>confidential interviews complete</span></div><div class="threshold-line">${[1,2,3,4,5].map(n=>`<i class="filled">${n}</i>`).join("")}<i>6</i><i>7</i></div><div class="privacy-boundary"><span>Visible to sponsor</span><p>Aggregate invitation and completion progress</p><span>Never visible</span><p>Who started, who submitted, answers, excerpts, or individual scores</p></div></div>`,
    participant:`<div class="interview-surface"><header><span>Organizational Capacity Diagnostic</span><b>Private draft saved</b></header><div class="question-progress"><i></i></div><small>Question 6 of 18 · Decision movement</small><h3>When a decision moves cleanly, what information, authority, and coordination are in place?</h3><div class="answer-field">Everyone operates from the same data, managers know the thresholds they own, and every handoff identifies one accountable next owner.<span>Visible only to you</span></div><button>Save and continue</button></div>`,
    steward:`<div class="steward-progress"><header><div><span>Collection stewardship</span><strong>One action may protect momentum</strong></div><b>Day 8 of 14</b></header><div class="progress-metrics"><article><strong>7</strong><span>Invited</span></article><article><strong>5</strong><span>Completed</span></article><article><strong>1</strong><span>Accepted · pending</span></article><article><strong>1</strong><span>Not accepted</span></article></div><div class="steward-prompt"><span>Suggested steward action</span><strong>Ask the sponsor to reinforce why cross-functional participation matters—without identifying or pressuring a specific participant.</strong></div></div>`
  },
  design:{
    sponsor:`<div class="design-studio"><header><div><span>Perspective design</span><strong>Choose who can reveal the system</strong></div><b>7 planned · POC range 5–10</b></header><div class="coverage-map"><article><span>Organizational level</span><strong>Executive · Functional · Manager · IC</strong></article><article><span>Execution proximity</span><strong>Strategy · Coordination · Delivery</strong></article><article><span>Functional lenses</span><strong>Commercial · Product · Operations · Customer</strong></article><article><span>Relationship to issue</span><strong>Direct · Peer · Cross-functional · Frontline</strong></article></div><div class="protocol-card"><span>Contextual protocol</span><h3>18 common questions generated from the approved context and perspective design.</h3><p>Sponsor may approve or request reason-coded AI reframing for sensitivity, clarity, or fit. No free-form edits, additions, or deletions.</p><button data-inspect="protocol">Inspect example</button></div></div>`,
    participant:`<div class="invitation-surface"><span>Why you were invited</span><h3>Your vantage point reveals a part of execution leadership cannot see alone.</h3><p>You were selected for your relationship to the work—not because the diagnostic assumes a problem with you or your team.</p><ul><li>One common 18-question protocol</li><li>Approximately 45–60 minutes</li><li>Private written responses</li><li>No individual findings or scores</li></ul></div>`,
    steward:`<div class="design-review"><header><span>Design quality review</span><strong>Does this group test—or merely confirm—the sponsor’s explanation?</strong></header><div class="design-check"><i>✓</i><div><strong>Execution coverage</strong><p>Strategy, coordination, and delivery are represented.</p></div></div><div class="design-check"><i>!</i><div><strong>Potential blind spot</strong><p>No perspective currently sees customer-risk escalation before renewal.</p></div></div><div class="design-check"><i>✓</i><div><strong>Protocol governance</strong><p>18 questions approved; one sensitivity reframe accepted.</p></div></div></div>`
  },
  frame:{
    sponsor:`<div class="guidance-surface"><header><span>Guidance Session · stopping point 1</span><b>30 minutes</b></header><h3>Turn the concern into a decision the diagnostic can responsibly inform.</h3><div class="prompt-grid">${["What is happening?","What matters most?","What is at risk?","What must be decided?","What changed or was tried?","What is sensitive?"].map((q,i)=>`<article><i>0${i+1}</i><strong>${q}</strong></article>`).join("")}</div><div class="context-outcome"><span>Approved context</span><strong>Whether to enforce a permanent ceiling on custom work while protecting retention and the core platform roadmap.</strong></div></div>`,
    participant:`<div class="participant-closure"><span>—</span><h3>No participant is invited yet.</h3><p>The sponsor and steward first approve the diagnostic context, perspective design, and common protocol. This prevents collection from beginning with an unbounded or leading inquiry.</p></div>`,
    steward:`<div class="guidance-agenda"><span>Steward agenda</span><h3>Challenge the explanation without taking ownership of the answer.</h3><ol><li>Separate visible symptoms from the execution demand.</li><li>Name the consequential decision and time horizon.</li><li>Surface prior attempts and sensitivities.</li><li>Confirm what the diagnostic can—and cannot—claim.</li></ol><div><strong>Completion gate</strong><p>Steward attestation and sponsor approval are separate from scheduling the meeting.</p></div></div>`
  }
};

const inspectors={
  convergence:["Evidence convergence","Decision exceptions recur across commercial, product, and customer vantage points. No individual quote is exposed."],counterpoint:["Counterpoint retained","Some evidence suggests information latency—not unclear authority—may be the dominant mechanism."],confidence:["Moderate confidence","Patterns converge, but one competing explanation remains material. The Brief does not overstate certainty."],disclosure:["Disclosure review","Unique titles, locations, client names, and identifying incidents are generalized or excluded before evidence becomes synthesis-eligible."],uncertainty:["What would change our interpretation?","If timely customer-risk information does not reduce escalation, unclear decision authority becomes the stronger explanation."],protocol:["Question governance","Example: “When a decision moves cleanly, what information, authority, and coordination are in place?” Every participant receives the same core question."],default:["Why leadership can trust this","The platform separates observation from inference, preserves counterevidence, and enforces confidentiality before organizational findings appear."]
};

let pressure="retention",scope="organization",phaseIndex=0,lens="sponsor",notesVisible=true,clerk;
const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)];
const accessView=q("[data-presenter-access]"),accessStatus=q("[data-presenter-access-status]"),signIn=q("[data-presenter-sign-in]"),experience=q("[data-presenter-experience]"),signOut=q("[data-presenter-sign-out]");

function loadScript(src,key){return new Promise((resolve,reject)=>{const value=document.createElement("script");value.async=true;value.crossOrigin="anonymous";if(key)value.dataset.clerkPublishableKey=key;value.src=src;value.onload=resolve;value.onerror=reject;document.head.append(value);});}
async function presenterRequest(path){const token=await clerk?.session?.getToken({organizationId:clerk?.organization?.id});const response=await fetch(path,{credentials:"same-origin",headers:{Accept:"application/json",...(token?{Authorization:`Bearer ${token}`}:{})}});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error||"Presenter access unavailable.");return payload;}
async function activeOrganization(){if(clerk.organization)return true;let memberships=clerk.user?.organizationMemberships||[],totalCount=memberships.length;if(typeof clerk.user?.getOrganizationMemberships==="function"){const response=await clerk.user.getOrganizationMemberships({pageSize:2});memberships=response?.data||[];totalCount=response?.totalCount??memberships.length;}let organization=totalCount===1&&memberships.length===1?memberships[0].organization.id:null;if(!organization){const token=await clerk?.session?.getToken();const response=await fetch("/api/workspace/organization-bootstrap",{credentials:"same-origin",headers:{Accept:"application/json",...(token?{Authorization:`Bearer ${token}`}:{})}});if(!response.ok)return false;organization=(await response.json()).organization;}await clerk.setActive({organization});clerk.session?.clearCache();return true;}

function renderPressureOptions(){q("[data-pressure-options]").innerHTML=Object.entries(pressures).map(([id,item])=>`<button type="button" data-pressure="${id}" aria-pressed="${id===pressure}">${item.label}</button>`).join("");}
function renderScopeOptions(){q("[data-scope-options]").innerHTML=Object.entries(scopes).map(([id,item])=>`<button type="button" data-scope="${id}" aria-pressed="${id===scope}">${item.label}</button>`).join("");}
function renderPerspective(id="sales"){const panel=q("[data-perspective-panel]");if(!panel)return;const item=perspectiveViews[id];panel.innerHTML=`<span>What this vantage point can observe</span><h3>${item.role}</h3><p>${item.observes}</p><div><strong>Protected distinction</strong><small>This describes observational access—not the participant’s answer, score, or inferred finding.</small></div>`;}
function renderReasoning(id="escalation"){const panel=q("[data-reasoning-panel]");if(!panel)return;const item=reasoningViews[id];panel.innerHTML=`<header><div><span>${item.type}</span><h3>${item.label}</h3></div><b>${item.status}</b></header><p>${item.statement}</p><div class="vantage-support"><span>Converges across</span>${item.vantages.map(vantage=>`<i>${vantage}</i>`).join("")}</div><div class="reasoning-tests"><article><span>What strengthens it</span><ul>${item.strengthens.map(signal=>`<li>${signal}</li>`).join("")}</ul></article><article><span>What weakens it</span><p>${item.weakens}</p></article><article class="change-test"><span>What would change our interpretation?</span><p>${item.change}</p></article></div><small class="reasoning-privacy">De-identified, disclosure-reviewed organizational evidence · no raw responses or attributable excerpts</small>`;}
function renderInspector(id="default"){const [title,body]=inspectors[id]||inspectors.default;q("[data-inspector-title]").textContent=title;q("[data-inspector-content]").innerHTML=`<p>${body}</p><div class="inspector-boundary"><span>Protected boundary</span><strong>Aggregate organizational evidence only</strong><small>No raw response, attributable excerpt, or individual score appears here.</small></div>`;}
function render(){const phase=phases[phaseIndex],selected=pressures[pressure],selectedScope=scopes[scope];renderPressureOptions();renderScopeOptions();q("[data-pressure-label]").textContent=`${selected.context} · ${selectedScope.context}`;q("[data-decision-title]").textContent=selected.decision;q("[data-decision-context]").textContent=`Focus: ${selectedScope.decision}. ${selected.description} ${selectedScope.description}`;q("[data-status]").textContent=phase.status;q("[data-surface-kicker]").textContent=phase.kicker;q("[data-surface-title]").textContent=phase.title;q("[data-state-summary]").innerHTML=`<span>${phase.label}</span><p>${phase.summary}</p>`;q("[data-surface-content]").innerHTML=surfaces[phase.id][lens];renderPerspective();renderReasoning();q("[data-note-objective]").textContent=phase.objective;q("[data-note-question]").textContent=phase.question;q("[data-note-proof]").textContent=phase.proof;q("[data-note-transition]").textContent=phase.transition;q("[data-timeline]").innerHTML=phases.slice().reverse().map(item=>{const index=phases.findIndex(p=>p.id===item.id);return `<button type="button" data-phase="${index}" aria-current="${index===phaseIndex?'step':'false'}"><i></i><span>${item.label}</span><small>${item.sub}</small></button>`;}).join("");qa("[data-lens]").forEach(button=>button.setAttribute("aria-pressed",String(button.dataset.lens===lens)));q("[data-advance]").textContent=phaseIndex<phases.length-1?`Continue to ${phases[phaseIndex+1].label}`:"Return to the revelation";q("[data-presenter-note]").hidden=!notesVisible;q("[data-notes-toggle]").textContent=notesVisible?"Hide presenter intelligence":"Show presenter intelligence";q("[data-notes-toggle]").setAttribute("aria-expanded",String(notesVisible));q("[data-surface-content]").classList.remove("surface-enter");requestAnimationFrame(()=>q("[data-surface-content]").classList.add("surface-enter"));renderInspector();}

document.addEventListener("click",event=>{const pressureButton=event.target.closest("[data-pressure]"),scopeButton=event.target.closest("[data-scope]"),phaseButton=event.target.closest("[data-phase]"),lensButton=event.target.closest("[data-lens]"),inspectButton=event.target.closest("[data-inspect]"),perspectiveButton=event.target.closest("[data-perspective]"),reasoningButton=event.target.closest("[data-reasoning]");if(pressureButton){pressure=pressureButton.dataset.pressure;render();}else if(scopeButton){scope=scopeButton.dataset.scope;render();}else if(phaseButton){phaseIndex=Number(phaseButton.dataset.phase);render();}else if(lensButton){lens=lensButton.dataset.lens;render();}else if(inspectButton){qa("[data-inspect]").forEach(button=>button.classList.toggle("active",button===inspectButton));renderInspector(inspectButton.dataset.inspect);}else if(perspectiveButton){qa("[data-perspective]").forEach(button=>button.classList.toggle("active",button===perspectiveButton));renderPerspective(perspectiveButton.dataset.perspective);}else if(reasoningButton){qa("[data-reasoning]").forEach(button=>button.classList.toggle("active",button===reasoningButton));renderReasoning(reasoningButton.dataset.reasoning);}});
q("[data-advance]").addEventListener("click",()=>{phaseIndex=phaseIndex<phases.length-1?phaseIndex+1:0;render();});
q("[data-reset]").addEventListener("click",()=>{pressure="retention";scope="organization";phaseIndex=0;lens="sponsor";notesVisible=true;render();});
q("[data-notes-toggle]").addEventListener("click",()=>{notesVisible=!notesVisible;render();});
signOut.addEventListener("click",()=>clerk?.signOut({redirectUrl:"/workspace/presenter-demo.html"}));

async function initialize(){try{const configResponse=await fetch("/api/workspace/config",{credentials:"same-origin",headers:{Accept:"application/json"}}),config=await configResponse.json();if(!configResponse.ok)throw new Error(config.error||"Workspace sign-in is unavailable.");await loadScript(config.clerkUiUrl);await loadScript(config.clerkJsUrl,config.publishableKey);clerk=window.Clerk;await clerk.load({ui:{ClerkUI:window.__internal_ClerkUICtor}});if(!clerk.user){accessStatus.textContent="Sign in with an authorized Senger Advisory presenter account.";clerk.mountSignIn(signIn,{fallbackRedirectUrl:"/workspace/presenter-demo.html"});return;}if(!(await activeOrganization()))throw new Error("Select an authorized Senger Advisory organization before opening presenter mode.");const data=await presenterRequest("/api/workspace/presenter-demo-access");accessStatus.textContent=`Presenter authority confirmed · ${data.access.authority.replaceAll("-"," ")}`;accessView.hidden=true;experience.hidden=false;signOut.hidden=false;render();}catch(error){accessStatus.textContent=error.message;}}
initialize();
